TasksTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: TasksTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: createdAt
        AttributeType: S
      - AttributeName: title
        AttributeType: S
      - AttributeName: description
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: title
        KeySchema:
          - AttributeName: title
            KeyType: HASH
        Projection:
          ProjectionType: ALL
